#!/usr/bin/env python3
"""Generate a D1s eGON image entering the locally verified ROM FEL vector."""

import argparse
from pathlib import Path
import struct

from pack_spl import CHECKSUM_STAMP, validate_spl


def make_fel_spl() -> bytes:
    image = bytearray(1024)
    struct.pack_into('<I', image, 0, 0x0600006F)
    image[4:12] = b'eGON.BT0'
    struct.pack_into('<II', image, 12, CHECKSUM_STAMP, len(image))
    # Cold ROM enables I-cache: turn it off before FEL overwrites this SRAM.
    struct.pack_into('<4I', image, 0x60,
                     0x7C10F073,
                     0x0000100F,
                     0x02000293,
                     0x00028067)
    checksum = sum(struct.unpack('<256I', image)) & 0xFFFFFFFF
    struct.pack_into('<I', image, 12, checksum)
    return validate_spl(bytes(image), 'FEL SPL')


def make_header(image: bytes) -> str:
    rows = [', '.join(f'0x{x:02x}' for x in image[i:i + 16])
            for i in range(0, len(image), 16)]
    return ('/* Generated by tools/make_fel_spl.py. */\n'
            '#pragma once\n#include <stdint.h>\n\n'
            'static const uint8_t fel_spl_image[1024] = {\n' +
            ''.join('    ' + row + ',\n' for row in rows) + '};\n')


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--binary', type=Path, default=root / 'main/fel_spl.bin')
    parser.add_argument('--header', type=Path, default=root / 'main/fel_spl.h')
    args = parser.parse_args()
    image = make_fel_spl()
    args.binary.write_bytes(image)
    args.header.write_text(make_header(image))


if __name__ == '__main__':
    main()
